### ISSUE TITLE
Inbrief Survey

### ISSUE THREAD

**Issue by hessionra** [ICPI/OCM#30]
Discussed at OCM on 7/12; planning to distribute a survey to Inbrief listserv to see how people view the Inbrief, use it, and its efficiency.

Reviewing draft survey at OCM on 7/19 @shapaklyak

**Comment by shapaklyak** [comment]
@hessionra i plan to update based on emailed feedback and throw it into google forms - planning on doing this by Wednesday 7/25 COB

**Comment by jb3436** [comment]
Google Form Survey [Link ](https://docs.google.com/forms/d/e/1FAIpQLSc5iW6UXknwCDbLwY74P8HACnDlUMoPpN1cr9Jv0w96g7ctUA/viewform)
--
I will make some slight modifications. 

FYI @hessionra @shapaklyak

**Comment by shapaklyak** [comment]
@jb3436 sounds good. thanks!

**Comment by hessionra** [comment]
@jb3436 please let us know if you have any updates for the OCM e-check in this week, or if we should table until next week!

**Comment by shapaklyak** [comment]
@hessionra i emailed a few comments..let me know if it didn't go through

**Comment by jb3436** [comment]
Notes on Meeting Metrics
--
FYI @hessionra @shapaklyak @kkale25 Feel free to add more resources in additional comments. 

**Things to Track**
  - Timeliness
  - Attendance
  - Time Planned vs. Time Spent
  - Action items created during the meeting
  - Decisions made
  - Participation and engagement: How many people speak up

**Type of Meetings**
  - What is the event type?
    - Status update meetings
    - Information sharing meeting
    - Decision making meeting
    - Problem solving meeting
    - Innovation meeting
    - Team building meeting
  - Meeting Intention
  - Meeting Format
  - Meeting Participation

**Periodic Table of Meetings**
![image](https://user-images.githubusercontent.com/13006198/46505681-d93c5d80-c7ff-11e8-9f40-54d0de55ccd4.png)

[https://blog.lucidmeetings.com/blog/periodic-table-of-meetings](https://blog.lucidmeetings.com/blog/periodic-table-of-meetings)

**Meeting maturity framework**
![image](https://user-images.githubusercontent.com/13006198/46505701-e5c0b600-c7ff-11e8-99f3-163deea94d72.png)

[https://blog.lucidmeetings.com/blog/meeting-performance-maturity-model](https://blog.lucidmeetings.com/blog/meeting-performance-maturity-model)

In our attempt to move up the meeting maturity framework, we are evaluating the inbrief and will evaluate other meetings to continue to grow.

**Meeting Maturity**

**Level 1: Ad Hoc - &quot;Winging It&quot;**
  - Almost no repeatable meeting process.
  - Meetings are poorly controlled and reactive.
  - Success is entirely dependent on the individual meeting leader&#39;s ability.

**Level 2: Repeatable - Dependent**
  - Meeting success is managed by one or more skilled individuals who &quot;know what to do&quot;.
  - Individuals improve through independent learning, but there is no organization-owned focus on meetings.

**Level 3: Defined - Standardized**
  - Standard meeting processes are defined for key meetings within the organization.
  - The organization provides some training and guidance on how to run meetings.
  - Individuals tailor their processes from the organization&#39;s standards.

**Level 4: Managed - Core Competency**
  - The organization monitors and measures meeting performance numbers.
  - Standard meeting processes get updated, and new ones are added as needed.
  - Facilitation is a recognized and supported skill.
  - Individuals become accountable for achieving meeting performance expectations.

**Level 5: Optimized - World Class**
  - The organization has &quot;a way&quot; to meet that embeds their values and strategic priorities.
  - The organization maintains critical focus on meeting effectiveness.
  - Feedback loops are in place to update and adapt meeting processes.
  - The organization ensures access to trained facilitation resources.
  - Meeting performance is job performance. Individuals expect effective meetings because they meet to get work done.

From [https://blog.lucidmeetings.com/blog/meeting-performance-maturity-model](https://blog.lucidmeetings.com/blog/meeting-performance-maturity-model)

**TEAM CADENCE MEETINGS**
**Intention**
  - Ensure group cohesion
  - Drive execution

**Examples**
  - the Weekly Team Meeting
  - the Daily Huddle
  - the Shift-Change Meeting
  - a Regular Committee Meeting

**PROGRESS CHECKS**
**Intention**
  - Maintain project momentum
  - Ensure mutual accountability

**Examples**
  - the Project Status Meeting
  - the Client Check-In

**ONE-ON-ONES**
**Intention**
  - Career and personal development
  - Individual accountability
  - Relationship maintenance

**Examples**
  - the Manager-Employee One-on-One
  - a Coaching Session
  - a Mentorship Meeting
  - the &quot;Check In&quot; with an Important Stakeholder

**ACTION REVIEWS**
**Intention**
  - Learning: gain insight
  - Develop confidence
  - Generate recommendations for change

**Examples**
  - Project and Agile Retrospectives
  - After Action Reviews and Before Action Reviews (Military)
  - Pre-Surgery Meetings (Healthcare)
  - Win/Loss Review (Sales)



**Attendance**
- Track attendance
- In person &amp; Phone

**Additional Metric**

Were Follow Up/action items identified, recorded, and tracked?
  - What was the purpose of the meeting?
    - Was the purpose met, and to what extent? (fully, somewhat or not at all)
    - Were planned decisions made as required and expected?
    - If decisions were not made as expected, why not?
    - Based on the results of the meeting, was this meeting necessary and worthwhile?

From \&lt;[https://www.ittoolkit.com/articles/post-meeting-assessment](https://www.ittoolkit.com/articles/post-meeting-assessment)\&gt;



Articles on Meeting Metrics, Effectiveness, and Taxonomies
--
  -The 16 Types of Business Meetings (and Why They Matter)
[https://blog.lucidmeetings.com/blog/16-types-of-business-meetings](https://blog.lucidmeetings.com/blog/16-types-of-business-meetings)
-  [https://blog.lucidmeetings.com/blog/6-meeting-metrics-to-collect-in-every-meeting-you-run](https://blog.lucidmeetings.com/blog/6-meeting-metrics-to-collect-in-every-meeting-you-run)
  - [https://www.google.com/search?{google:acceptedSuggestion}oq=what+are+the+measures+of+a+successful+meeting&amp;sourceid=chrome&amp;ie=UTF-8&amp;q=what+are+the+measures+of+a+successful+meeting](https://www.google.com/search?%7bgoogle:acceptedSuggestion%7doq=what+are+the+measures+of+a+successful+meeting&amp;sourceid=chrome&amp;ie=UTF-8&amp;q=what+are+the+measures+of+a+successful+meeting)
  - [https://www.socialtables.com/blog/event-planning/measuring-event-and-meeting-success/](https://www.socialtables.com/blog/event-planning/measuring-event-and-meeting-success/)
  - [https://activategroupinc.com/2015/07/how-do-you-measure-the-success-of-a-meeting/](https://activategroupinc.com/2015/07/how-do-you-measure-the-success-of-a-meeting/)
  - [https://www.idashboards.com/blog/2016/11/30/how-to-know-if-your-meeting-was-effective/](https://www.idashboards.com/blog/2016/11/30/how-to-know-if-your-meeting-was-effective/)
  - [https://blog.lucidmeetings.com/blog/6-meeting-metrics-to-collect-in-every-meeting-you-run](https://blog.lucidmeetings.com/blog/6-meeting-metrics-to-collect-in-every-meeting-you-run)
  - [http://www.avasbutler.com/four-techniques-to-evaluate-meeting-effectiveness-3-team-effectiveness-chart/#.W22XRs5Ki73](http://www.avasbutler.com/four-techniques-to-evaluate-meeting-effectiveness-3-team-effectiveness-chart/#.W22XRs5Ki73)
  - [https://www.ittoolkit.com/articles/post-meeting-assessment](https://www.ittoolkit.com/articles/post-meeting-assessment)
  - [https://blog.lucidmeetings.com/blog/16-types-of-business-meetings](https://blog.lucidmeetings.com/blog/16-types-of-business-meetings)

**Comment by hessionra** [comment]
Announced survey during Inbrief 10/15, will send email out to Inbrief listserv 10/17

**Comment by hessionra** [comment]
Results collected, analyzed, and feedback is being implemented in 2019.
